[project]
name = "invest-backtesting"
version = "0.1.0"
description = "Simple backtesting of my investment"
readme = "README.md"
authors = [
    { name = "deepthought", email = "deepthought@postech.ac.kr" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "click>=8.2.1",
    "finance-datareader>=0.9.94",
    "fonttools>=4.60.2",
    "idna>=3.15",
    "lxml>=6.1.0",
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "pillow>=12.3.0",
    "plotly>=5.24.1",
    "requests>=2.32.4",
    "soupsieve>=2.8.4",
    "urllib3>=2.7.0",
]

[project.scripts]
backtesting = "invest_backtesting.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
